# Generated by Django 3.2.6 on 2021-08-11 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateau', '0002_alter_dessert_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dessert',
            options={'verbose_name': 'black sesame dessert', 'verbose_name_plural': 'black sesame desserts'},
        ),
    ]
